---
name: "Release Workflow"

"on":
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

concurrency:
  group: "${{ github.workflow }}-${{ github.ref_name }}"
  cancel-in-progress: true

jobs:
  release_notes:
    timeout-minutes: 30
    name: Create changelog on tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate changelog
        id: generate_changelog
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path_filters: "changelog_generator/"
      - name: Create Release note
        id: create_release
        uses: ncipollo/release-action@a2e71bdd4e7dab70ca26a852f29600c98b33153e  # 1.12.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          tag: ${{ github.ref }}
          name: Release ${{ steps.get_version_and_tag.outputs.tag }}
          body: ${{ env.CHANGELOG }}
