name: "Validate Pull Request"

on:
  pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref }}
    cancel-in-progress: true

jobs:
  github-actions-validator:
    name: "Github-actions-validator"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lumapps/github-actions-validator@master
  preview_changelog:
    timeout-minutes: 30
    name: Render the changelog in a PR comment to preview changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          # create the master branch
          git branch ${{ github.base_ref }} origin/${{ github.base_ref }}
          # create the pr branch
          git branch ${{ github.head_ref }} origin/${{ github.head_ref }}
      - name: Generate changelog
        id: generate_changelog
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path_filters: "changelog_generator/"
          target: ${{ github.base_ref }}..${{ github.head_ref }}
      - uses: kanga333/comment-hider@bbdf5b562fbec24e6f60572d8f712017428b92e0
        name: Hide previous comments
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Add PR Comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: process.env.CHANGELOG
            })
